package AUApp::Model::Auswertung;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'AUApp::Auswertung',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=au;host=localhost;port=5432',
        user => 'au',
        password => 'Vienna',
    }
);

=head1 NAME

AUApp::Model::Auswertung - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<AUApp>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<AUApp::Auswertung>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

U-GROUPINFRA\gitzelp,S-1-5-21-3641078771-3653456904-245653651-141386

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
