#!/usr/bin/bash
script/auapp_create.pl model Auswertung DBIC::Schema  AUApp::Auswertung create=static db_schema="au_extension,dummy" moniker_parts='[qw(schema name)]' constraint="$1" overwrite_modifications=1 debug=1 'dbi:Pg:dbname=au;host=localhost;port=5432' au Vienna 
