#!/usr/bin/bash
script/auapp_create.pl model Auswertung DBIC::Schema  AUApp::Auswertung create=static db_schema="au_extension,dummy" moniker_parts='[qw(schema name)]' exclude='\A(f_type_d|f_type_r|f_type_rz|l\d{1})\z' overwrite_modifications=1 debug=1 'dbi:Pg:dbname=au;host=localhost;port=5432' au Vienna 
