SELECT 'dynamiccall       ' ||  COUNT(*) FROM dynamiccall;
SELECT 'flow_input        ' ||  COUNT(*) FROM flow_input;
SELECT 'indices           ' ||  COUNT(*) FROM indices;
SELECT 'logical_physical  ' ||  COUNT(*) FROM logical_physical;
SELECT 'parameter_registry' ||  COUNT(*) FROM parameter_registry;
SELECT 'printer           ' ||  COUNT(*) FROM printer;
SELECT 'program_call      ' ||  COUNT(*) FROM program_call;
SELECT 'program_error     ' ||  COUNT(*) FROM program_error;
SELECT 'program_flow      ' ||  COUNT(*) FROM program_flow;
SELECT 'program_input     ' ||  COUNT(*) FROM program_input;
SELECT 'program_output    ' ||  COUNT(*) FROM program_output;
SELECT 'program_using     ' ||  COUNT(*) FROM program_using;
SELECT 'screen            ' ||  COUNT(*) FROM screen;
SELECT 'sequential        ' ||  COUNT(*) FROM sequential;
SELECT 'step_argument     ' ||  COUNT(*) FROM step_argument;
SELECT 'step_condition    ' ||  COUNT(*) FROM step_condition;
SELECT 'superdescriptor   ' ||  COUNT(*) FROM superdescriptor;
SELECT 'token             ' ||  COUNT(*) FROM token;
SELECT 'working_storage   ' ||  COUNT(*) FROM working_storage;
SELECT 'ddm               ' ||  COUNT(*) FROM ddm;
SELECT 'indexed_sequential' ||  COUNT(*) FROM indexed_sequential;
SELECT 'program           ' ||  COUNT(*) FROM program;
SELECT 'step              ' ||  COUNT(*) FROM step;
SELECT 'flow              ' ||  COUNT(*) FROM flow;
SELECT 'input_output      ' ||  COUNT(*) FROM input_output;
SELECT 'measure           ' ||  COUNT(*) FROM measure;
SELECT 'type              ' ||  COUNT(*) FROM type;
SELECT 'abstractlibrary   ' ||  COUNT(*) FROM abstractlibrary;
